=== uo258525/practica2/Ejercicio-1/Tarea-2/rutas.dtd
<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta (tipo, dificultad-ruta, inicio, agencia, descripcion, personas-aptas, referencias,recomendacion,hitos)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT dificultad-ruta (#PCDATA)>
<!ELEMENT inicio (fecha-inicio?,hora-inicio?,lugar-inicio,direccion-inicio)>
<!ELEMENT fecha-inicio (#PCDATA)>
<!ELEMENT hora-inicio (#PCDATA)>
<!ELEMENT lugar-inicio (#PCDATA)>
<!ELEMENT direccion-inicio (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT personas-aptas (apta+)>
<!ELEMENT apta (#PCDATA)>
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT recomendacion (#PCDATA)>
<!ELEMENT hitos (hito+)>
<!ELEMENT hito (nombre-hito, descripcion-hito, distancia-hito,tiempo-hito?, fotos-hito+, videos-hito*)>
<!ELEMENT nombre-hito (#PCDATA)>
<!ELEMENT descripcion-hito (#PCDATA)>
<!ELEMENT distancia-hito (#PCDATA)>
<!ELEMENT tiempo-hito (#PCDATA)>
<!ELEMENT fotos-hito (foto-hito+)>
<!ELEMENT foto-hito (#PCDATA)>
<!ELEMENT videos-hito (video-hito+)>
<!ELEMENT video-hito (#PCDATA)>
<!ATTLIST ruta
nombre CDATA #REQUIRED
duracion CDATA #REQUIRED>
<!ATTLIST inicio
longitud CDATA #REQUIRED
latitud CDATA #REQUIRED
altitud CDATA #REQUIRED>
<!ATTLIST hito
longitud CDATA #REQUIRED
latitud CDATA #REQUIRED
altitud CDATA #REQUIRED>
<!ATTLIST distancia-hito
unidad CDATA #REQUIRED>
<!ATTLIST tiempo-hito
unidad CDATA #REQUIRED>

=== uo258525/practica2/Ejercicio-1/Tarea-2/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
<rutas>
<ruta nombre="Ruta a Viena" duracion="8 días">
	<tipo>Turística </tipo>
	<dificultad-ruta> Fácil</dificultad-ruta>
	<inicio latitud="43.563465" longitud="-6.033343" altitud="127">
		<fecha-inicio>2020-10-14</fecha-inicio>
		<hora-inicio>09:00:00</hora-inicio>
		<lugar-inicio>Aeropuerto de Asturias (Santiago del Monte)</lugar-inicio>
		<direccion-inicio>33459 Santiago del Monte, Asturias</direccion-inicio>
	</inicio>		
	<agencia>Sin agencia</agencia>
	<descripcion>Esta ruta tiene origen en Asturias y destino en Viena. 
	Se realizará en avión y se harán paradas en Paris, Berlín, Berna y finalmente concluirá en Viena.
	Cada parada durará 2 días para que los turistas puedan hacer visitas a las ciudades correspondientes y hacer turismo.
	</descripcion>
	<personas-aptas>
		<apta>Mayores de 18</apta>
		<apta>Se puede ir con niños</apta>
	</personas-aptas>
	<referencias>
		<referencia>https://es.parisinfo.com/</referencia>
		<referencia>https://www.visitberlin.de/es</referencia>
		<referencia>https://viajerosonline.org/suiza-berna-informacion-turistica-y-guia-de-viaje-de-la-ciudad-de-berna/</referencia>
		<referencia>https://www.viajaraviena.com/</referencia>
	</referencias>
	<recomendacion>7</recomendacion>
<hitos>
		<hito latitud="48.8032" longitud="2.3488" altitud="35">
			<nombre-hito>Paris</nombre-hito>
			<descripcion-hito>
				La capital de Francia es el destino turístico más popular del mundo.
				Paris ha sido un centro cultural y artístico relevante en la historia occidental.
				Entre los monumentos más interesantes que visitar se encuentran la Torre Eiffel, la catedral de Notre Dame, el Arco de Triunfo y el Panteón entre otros.
			</descripcion-hito>
			<distancia-hito unidad="km">1197'8</distancia-hito>
			<tiempo-hito unidad="horas">1'45</tiempo-hito>
			<fotos-hito>
				<foto-hito>https://commons.wikimedia.org/wiki/File:Paris_-_Eiffelturm_und_Marsfeld2.jpg</foto-hito>
				<foto-hito>https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Cath%C3%A9drale_Notre-Dame_de_Paris%2C_20_March_2014.jpg/800px-Cath%C3%A9drale_Notre-Dame_de_Paris%2C_20_March_2014.jpg</foto-hito>
				<foto-hito>https://cdn.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_502,h_402/https://sobrefrancia.com/wp-content/blogs.dir/5//Arco-del-Triunfo-en-Paris.jpg</foto-hito>
				<foto-hito>http://www.guiapracticaparis.com/imagenes/panteon-de-paris.jpg</foto-hito>
			</fotos-hito>
			<videos-hito>
				<video-hito>https://www.youtube.com/watch?v=_n6GHaADUOc</video-hito>
			</videos-hito>
		</hito>


		<hito latitud="52.5186" longitud="13.4081" altitud="34">
			<nombre-hito>Berlín</nombre-hito>
			<descripcion-hito>
				La capital de Alemania es la ciudad más poblada del país y de Europa Central.
				Berlín es una ciudad histórica con un gran ámbito cultural y artístico.
				Entre los monumentos más interesantes que visitar se encuentran el muro de Berlín, puerta de Brandemburgo y el memorial del Holocausto entre otros.
			</descripcion-hito>
			<distancia-hito unidad="km">1054</distancia-hito>
			<tiempo-hito unidad="horas">1'47</tiempo-hito>
			<fotos-hito>
				<foto-hito>https://imagenes.20minutos.es/files/image_656_370/uploads/imagenes/2014/05/01/169466.jpg</foto-hito>
				<foto-hito>https://www.agentedeviajes.info/wp-content/uploads/2018/04/BERL%C3%8DN-UNA-CIUDAD-CON-HISTORIA.jpg</foto-hito>
				<foto-hito>https://www.laguiadeberlin.com/wp-content/uploads/2018/05/muro-berlin-480-1280x720.jpg</foto-hito>
				<foto-hito>https://laguiadeberlin.com/wp-content/uploads/2018/01/museo-holocausto-de-berlin.jpg</foto-hito>
			</fotos-hito>
			<videos-hito>
				<video-hito>https://www.youtube.com/watch?v=kgcY4yMKuto</video-hito>
			</videos-hito>
		</hito>


		<hito latitud="46.9489" longitud="7.40737" altitud="540">
			<nombre-hito>Berna</nombre-hito>
			<descripcion-hito>
				La capital de Suiza es una ciudad administrativa y de funcionarios, aunque también de congresos y turística.
				La ciudad vieja de Berna está inscrita en la lista de Patrimonio de la Humanidad de la Unesco desde 1983,
				gracias a su arquitectura medieval conservada a través de los siglos.
				Entre los monumentos más interesantes que visitar se encuentran la catedral, la ciudad vieja de Berna y la torre del reloj entre otros.
			</descripcion-hito>
			<distancia-hito unidad="km">958'8</distancia-hito>
			<tiempo-hito unidad="horas">1'30</tiempo-hito>
			<fotos-hito>
				<foto-hito>https://upload.wikimedia.org/wikipedia/commons/4/45/M%C3%BCnster_%28Bern%29.jpg</foto-hito>
				<foto-hito>https://upload.wikimedia.org/wikipedia/commons/b/bf/CH_Bern_Kramgasse.jpg</foto-hito>
				<foto-hito>https://upload.wikimedia.org/wikipedia/commons/1/17/Zytglogge_01.jpg</foto-hito>
			</fotos-hito>
			<videos-hito>
				<video-hito>https://www.youtube.com/watch?v=09_LW0N6iKE</video-hito>
			</videos-hito>
		</hito>

		<hito latitud="48.2092" longitud="16.3728" altitud="156">
			<nombre-hito>Viena</nombre-hito>
			<descripcion-hito>
				La capital de Austria está situada a orillas del Danubio y se considera uno de los principales centros culturales mundiales.
				Es una de las capitales más antiguas de Europa, por lo que cuenta con un importante patrimonio artístico.
				Entre los lugares más interesantes que visitar se encuentran la ópera estatal de Viena, el museo de Historia del Arte, el palacio de Belvedere y la catedral de San Esteban.
			</descripcion-hito>
			<distancia-hito unidad="km">683</distancia-hito>
			<tiempo-hito unidad="horas">1'25</tiempo-hito>
			<fotos-hito>
				<foto-hito>http://www.efemeridespedrobeltran.com/es/imagenes/vienna.jpg</foto-hito>
				<foto-hito>https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Museo_de_Historia_del_Arte%2C_Viena%2C_Austria%2C_2020-01-31%2C_DD_152-154_HDR.jpg/1920px-Museo_de_Historia_del_Arte%2C_Viena%2C_Austria%2C_2020-01-31%2C_DD_152-154_HDR.jpg</foto-hito>
				<foto-hito>https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Palacio_Belvedere%2C_Viena%2C_Austria%2C_2020-02-01%2C_DD_90-92_HDR.jpg/524px-Palacio_Belvedere%2C_Viena%2C_Austria%2C_2020-02-01%2C_DD_90-92_HDR.jpg</foto-hito>
				<foto-hito>https://www.laguiadeviena.com/wp-content/uploads/2019/12/catedral-sanesteban-viena.jpg</foto-hito>
			</fotos-hito>
			<videos-hito>
				<video-hito>https://www.youtube.com/watch?v=sG7ud_coOgU</video-hito>
			</videos-hito>
		</hito>
	</hitos>
	</ruta>

<ruta nombre="Ruta a Roma" duracion="6 días">
	<tipo>Turística </tipo>
	<dificultad-ruta> Fácil</dificultad-ruta>
	<inicio latitud="38.775732" longitud="-9.135297" altitud="114">
		<fecha-inicio>2020-11-26</fecha-inicio>
		<hora-inicio>09:30:00</hora-inicio>
		<lugar-inicio>Aeropuerto de Lisboa</lugar-inicio>
		<direccion-inicio>Alameda das Comunidades Portuguesas, 1700-111 Lisboa, Portugal</direccion-inicio>
	</inicio>	
	<agencia>Sin agencia</agencia>
	<descripcion>Esta ruta tiene origen en Lisboa y destino en Roma. 
	Se realizará en avión y se harán paradas en Madrid, Londres y finalmente concluirá en Roma.
	Cada parada durará 2 días para que los turistas puedan hacer visitas a las ciudades correspondientes y hacer turismo.
	</descripcion>
	<personas-aptas>
		<apta>Mayores de 18</apta>
		<apta>Se puede ir con niños</apta>
	</personas-aptas>
	<referencias>
		<referencia>https://www.esmadrid.com/?utm_referrer=https%3A%2F%2Fwww.google.com%2F</referencia>
		<referencia>https://www.viajarlondres.com/</referencia>
		<referencia>https://blog-italia.com/ciudades-de-italia/roma/oficinas-de-turismo</referencia>		
	</referencias>
	<recomendacion>8</recomendacion>

	<hitos>
	<hito latitud="40.4165" longitud="-3.70256" altitud="667">
	<nombre-hito>Madrid</nombre-hito>
	<descripcion-hito>La capital de España es un influyente centro cultural. 
	Esta ciudad es la combinación perfecta de oferta cultural, monumental y de ocio.
	Entre los lugares más interesantes que visitar se encuentran el parque de El Retiro, Plaza Mayor, Puerta del Sol y Gran Vía entre otros.	
	</descripcion-hito>
	<distancia-hito unidad="km">624'2</distancia-hito>
	<tiempo-hito unidad="horas">1'20</tiempo-hito>
	<fotos-hito>
	<foto-hito>https://guias-viajar.com/madrid/wp-content/uploads/2017/04/madrid-retiro-estanque-001.jpg</foto-hito>
	<foto-hito>https://commons.wikimedia.org/wiki/File:Plaza_Mayor_de_Madrid_06.jpg</foto-hito>
	<foto-hito>https://hiretail.es/wp-content/uploads/2020/01/puerta-del-sol-1280x720.jpg</foto-hito>
	<foto-hito>https://www.lhhoteles.com/backoffice/images/1019-gran-via-madrid.jpg</foto-hito>
	</fotos-hito>
	<videos-hito>
	<video-hito>https://www.youtube.com/watch?v=TH4h0sGkjkc</video-hito>
	</videos-hito>
	</hito>

	<hito latitud="51.50853" longitud=" -0.12574" altitud="11">
	<nombre-hito>Londres</nombre-hito>
	<descripcion-hito>Londres es la capital y mayor ciudad de Inglaterra y de Reino Unido. 
	Se considera una ciudad multicultural por la gran mezcla de culturas que posee y además una ciudad de la moda, para aquellos turistas amantes de las compras.
	Entre los lugares más interesantes que visitar se encuentran el Ojo de Londres, la Torre de Londres, Big Ben y el Puente de la Torre entre otros.	
	</descripcion-hito>
	<distancia-hito unidad="km">1727'7</distancia-hito>
	<tiempo-hito unidad="horas">2'30</tiempo-hito>
	<fotos-hito>
	<foto-hito>https://upload.wikimedia.org/wikipedia/commons/d/d6/London-Eye-2009.JPG</foto-hito>
	<foto-hito>https://www.vivireuropa.com/wp-content/uploads/2011/12/torre-de-londres.jpg.webp</foto-hito>
	<foto-hito>https://londresando.com/wp-content/uploads/2018/02/big-ben-londres-1024x682.jpeg</foto-hito>
	<foto-hito>https://miviaje.com/wp-content/uploads/2018/01/puente-de-la-torre-de-londres.jpg</foto-hito>
	</fotos-hito>
	<videos-hito>
	<video-hito>https://www.youtube.com/watch?v=citnxANTuz4</video-hito>
	</videos-hito>
	</hito>

	<hito latitud="41.8905" longitud="12.4942" altitud="37">
	<nombre-hito>Roma</nombre-hito>
